# Generated by Django 3.2.7 on 2021-09-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0)),
                ('location_id', models.CharField(blank=True, max_length=30)),
                ('building', models.IntegerField(default=0)),
                ('floor', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('row', models.CharField(blank=True, max_length=10)),
                ('column', models.CharField(blank=True, max_length=10)),
                ('pallet', models.IntegerField(default=0)),
                ('level', models.CharField(blank=True, max_length=10)),
                ('dimension', models.CharField(blank=True, max_length=20)),
                ('weight', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('quantity', models.IntegerField(default=0)),
                ('make_brand', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('price', models.FloatField(default=0)),
                ('product_link', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInMagento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmagento_id', models.CharField(blank=True, default=None, max_length=30)),
                ('mproduct_id', models.IntegerField(default=0)),
                ('mlocation_id', models.CharField(blank=True, max_length=30)),
                ('mbuilding', models.IntegerField(default=0)),
                ('mfloor', models.IntegerField(default=0)),
                ('munit', models.CharField(blank=True, max_length=20)),
                ('mrow', models.CharField(blank=True, max_length=10)),
                ('mcolumn', models.CharField(blank=True, max_length=10)),
                ('mpallet', models.IntegerField(default=0)),
                ('mlevel', models.CharField(blank=True, max_length=10)),
                ('mdimension', models.CharField(blank=True, max_length=20)),
                ('mweight', models.CharField(blank=True, max_length=20)),
                ('mdescription', models.TextField(blank=True, max_length=300)),
                ('mquantity', models.IntegerField(default=0)),
                ('mmake_brand', models.CharField(blank=True, max_length=50)),
                ('msource', models.CharField(blank=True, max_length=50)),
                ('mprice', models.FloatField(default=0)),
                ('mproduct_link', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInMagentoImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mimage', models.ImageField(upload_to='mproductImages')),
                ('mproduct', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='proactivehome.productinmagento')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productImages')),
                ('product', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='proactivehome.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_modified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_date', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('uploaded_product', models.BooleanField(default=True)),
                ('verified_product', models.BooleanField(default=False)),
                ('uploaded_product_magento', models.BooleanField(default=False)),
                ('product_pk', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='proactivehome.product')),
            ],
        ),
    ]
