# Generated by Django 3.2.7 on 2021-09-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proactivehome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimension',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
